// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqAn41erz5flWGzp93Xp4viwZ0FAyESdI',
    appId: '1:122212192408:web:8b80c057a82b87b64640ed',
    messagingSenderId: '122212192408',
    projectId: 'musica-d95f1',
    authDomain: 'musica-d95f1.firebaseapp.com',
    storageBucket: 'musica-d95f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBMtorcr2z5R0mEuGqzrp1VrfnRP_5J6A',
    appId: '1:122212192408:android:c09e15f741d8f65b4640ed',
    messagingSenderId: '122212192408',
    projectId: 'musica-d95f1',
    storageBucket: 'musica-d95f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQQCnKk683BW58GZWMIalrLWFYX6FXeFA',
    appId: '1:122212192408:ios:939ae8c8443a67604640ed',
    messagingSenderId: '122212192408',
    projectId: 'musica-d95f1',
    storageBucket: 'musica-d95f1.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqAn41erz5flWGzp93Xp4viwZ0FAyESdI',
    appId: '1:122212192408:web:5b55e70cb460795b4640ed',
    messagingSenderId: '122212192408',
    projectId: 'musica-d95f1',
    authDomain: 'musica-d95f1.firebaseapp.com',
    storageBucket: 'musica-d95f1.firebasestorage.app',
  );
}
